from datetime import datetime

from sqlalchemy import Boolean, Float, Integer, String, Text, DateTime, JSON
from sqlalchemy.orm import Mapped, mapped_column

from app.db.database import Base


class ExitSignal(Base):
    """
    An exit signal generated by the position monitor.

    Every time an exit strategy triggers (stop loss hit, profit target reached,
    indicator reversal, sentiment shift, EOD warning), a record is saved here
    and pushed via WebSocket.

    Urgency levels:
    - critical: Exit NOW (stop loss hit, EOD < 5 min)
    - high:     Exit soon (target hit, strong reversal, EOD warning)
    - medium:   Consider exiting (partial reversal, approaching stop, max hold)
    - low:      Heads up (partial target progress, mild sentiment shift)
    """
    __tablename__ = "exit_signals"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    position_id: Mapped[int] = mapped_column(Integer, nullable=False, index=True)
    symbol: Mapped[str] = mapped_column(String(10), nullable=False)
    exit_type: Mapped[str] = mapped_column(String(30), nullable=False)  # stop_loss, profit_target, indicator_reversal, sentiment_shift, eod_warning, max_hold_warning
    urgency: Mapped[str] = mapped_column(String(10), nullable=False)  # critical, high, medium, low
    trigger_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    current_price: Mapped[float] = mapped_column(Float, nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    details: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    acknowledged: Mapped[bool] = mapped_column(Boolean, default=False)
    acted_on: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
